### ISSUE TITLE
Weird distribution in sortval

### ISSUE THREAD

**Issue by vladdez** [s-ccs/ERPgnostics#12]
Why this value has such a weird distribution? It can not be the same trial all the time
![image](https://github.com/s-ccs/ERPgnostics/assets/33777074/ff66792d-5f16-4f21-8f38-ea948a94d544)

**Comment by behinger** [comment]
I agree, there should be only like 10% samebox

**Comment by vladdez** [comment]
the problem was in to tight xlimits
